apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
  labels:
    app: dev-app
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/DevUnnati/gitops-1.git
    targetRevision: main
    path: overlay/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev